/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASOCIACIONES_H_RPCGEN
#define _ASOCIACIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum Estado {
	OK = 0,
	Sustitucion = 1,
	NoEncontrado = 2,
};
typedef enum Estado Estado;

typedef int ID;

typedef char *Clave;

typedef char *Valor;

struct asociacion {
	Clave clave;
	Valor valor;
	struct asociacion *next;
};
typedef struct asociacion asociacion;

struct valor_estado {
	Valor valor;
	Estado s;
};
typedef struct valor_estado valor_estado;

struct asociacion_estado {
	asociacion *asoc;
	Estado s;
};
typedef struct asociacion_estado asociacion_estado;

struct ponerasociacion_1_argument {
	ID arg1;
	Clave arg2;
	Valor arg3;
};
typedef struct ponerasociacion_1_argument ponerasociacion_1_argument;

struct obtenerasociacion_1_argument {
	ID arg1;
	Clave arg2;
};
typedef struct obtenerasociacion_1_argument obtenerasociacion_1_argument;

struct borrarasociacion_1_argument {
	ID arg1;
	Clave arg2;
};
typedef struct borrarasociacion_1_argument borrarasociacion_1_argument;

#define ASOCIACIONES 0x20000002
#define ASOCIACIONESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define PonerAsociacion 1
extern  Estado * ponerasociacion_1(ID , Clave , Valor , CLIENT *);
extern  Estado * ponerasociacion_1_svc(ID , Clave , Valor , struct svc_req *);
#define ObtenerAsociacion 2
extern  valor_estado * obtenerasociacion_1(ID , Clave , CLIENT *);
extern  valor_estado * obtenerasociacion_1_svc(ID , Clave , struct svc_req *);
#define BorrarAsociacion 3
extern  Estado * borrarasociacion_1(ID , Clave , CLIENT *);
extern  Estado * borrarasociacion_1_svc(ID , Clave , struct svc_req *);
#define Enumerar 4
extern  asociacion_estado * enumerar_1(ID , CLIENT *);
extern  asociacion_estado * enumerar_1_svc(ID , struct svc_req *);
extern int asociaciones_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PonerAsociacion 1
extern  Estado * ponerasociacion_1();
extern  Estado * ponerasociacion_1_svc();
#define ObtenerAsociacion 2
extern  valor_estado * obtenerasociacion_1();
extern  valor_estado * obtenerasociacion_1_svc();
#define BorrarAsociacion 3
extern  Estado * borrarasociacion_1();
extern  Estado * borrarasociacion_1_svc();
#define Enumerar 4
extern  asociacion_estado * enumerar_1();
extern  asociacion_estado * enumerar_1_svc();
extern int asociaciones_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Estado (XDR *, Estado*);
extern  bool_t xdr_ID (XDR *, ID*);
extern  bool_t xdr_Clave (XDR *, Clave*);
extern  bool_t xdr_Valor (XDR *, Valor*);
extern  bool_t xdr_asociacion (XDR *, asociacion*);
extern  bool_t xdr_valor_estado (XDR *, valor_estado*);
extern  bool_t xdr_asociacion_estado (XDR *, asociacion_estado*);
extern  bool_t xdr_ponerasociacion_1_argument (XDR *, ponerasociacion_1_argument*);
extern  bool_t xdr_obtenerasociacion_1_argument (XDR *, obtenerasociacion_1_argument*);
extern  bool_t xdr_borrarasociacion_1_argument (XDR *, borrarasociacion_1_argument*);

#else /* K&R C */
extern bool_t xdr_Estado ();
extern bool_t xdr_ID ();
extern bool_t xdr_Clave ();
extern bool_t xdr_Valor ();
extern bool_t xdr_asociacion ();
extern bool_t xdr_valor_estado ();
extern bool_t xdr_asociacion_estado ();
extern bool_t xdr_ponerasociacion_1_argument ();
extern bool_t xdr_obtenerasociacion_1_argument ();
extern bool_t xdr_borrarasociacion_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASOCIACIONES_H_RPCGEN */
